icons = [
    "left-large",
    "right-large",
    "up-large",
    "arrow-circular-top-right",
    "warning-outline",
    "plus",
    "folder-filled",
    "paper-filled",
    "check-round-outline",
    "error-outline",
    "padlock2",
    "menu",
    "info-outline",
]