name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v4
    - run: pacman -Syu --noconfirm gtk4 gcc glib2-devel libadwaita rust pkgconf
    - name: Run tests
      run: cargo test
